theme = "blowfish"
baseURL = "https://mark-mccormack.github.io/machine-learning-implementations"
defaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Machine Learning Implementations'
publishDir = "docs"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

[params]
  colorScheme = 'congo'
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false