# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
baseURL = "https://mark-mccormack.github.io/machine-learning-implementations"
defaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Machine Learning Implementations'
publishDir = "docs"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[author]
  name = "My name"
  image = "img/author.jpg"
  headline = "A generally awesome human"
  bio = "A little bit about me"
  links = [
    { twitter = "https://twitter.com/username" }
  ]

[params]
  colorScheme = 'congo'

  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false