languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Machine Learning Implementations"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
dateFormat = "2 January 2006"

[author]
  name = "Mark McCormack"
  bio = "Lecturer | Postgraduate Researcher | Head Demonstrator | Tutor"
  links = [
    { github = "https://github.com/mark-mccormack/" },
  ]
