[[main]]
  name = "About"
  pageRef = "about"
  weight = 10
  url = "/about"

[[main]]
  name = "Vault"
  pageRef = "vault"
  weight = 20
  url = "/vault"

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 30
  url = "/categories"

[[main]]
  name = "GitHub"
  url = "https://github.com/mark-mccormack/"
  weight = 40
